# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'idm.ui'
#
# Created: Tue Jan  5 19:07:47 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(728, 554)
        MainWindow.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../Downloads/images/idm.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../Downloads/images/idm.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setToolTip(_fromUtf8(""))
        MainWindow.setAutoFillBackground(True)
        MainWindow.setIconSize(QtCore.QSize(30, 30))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tableWidget = QtGui.QTableWidget(self.tab)
        self.tableWidget.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tableWidget.setAutoScroll(False)
        self.tableWidget.setDragEnabled(True)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideLeft)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setGridStyle(QtCore.Qt.DashLine)
        self.tableWidget.setRowCount(12)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(7)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled|QtCore.Qt.ItemIsTristate)
        self.tableWidget.setItem(0, 2, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(0)
        self.tableWidget.verticalHeader().setMinimumSectionSize(0)
        self.gridLayout_2.addWidget(self.tableWidget, 0, 0, 1, 1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../Downloads/images/ongoing download.gif")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon1, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.textEdit = QtGui.QTextEdit(self.tab_3)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.gridLayout_3.addWidget(self.textEdit, 0, 0, 1, 1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("../Downloads/images/pause.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_3, icon2, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.tabWidget_2 = QtGui.QTabWidget(self.tab_2)
        self.tabWidget_2.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.listWidget = QtGui.QListWidget(self.tab_5)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.gridLayout_5.addWidget(self.listWidget, 0, 0, 1, 1)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("../Downloads/images/document.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_2.addTab(self.tab_5, icon3, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_7)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.listWidget_2 = QtGui.QListWidget(self.tab_7)
        self.listWidget_2.setObjectName(_fromUtf8("listWidget_2"))
        self.gridLayout_6.addWidget(self.listWidget_2, 0, 0, 1, 1)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("../Downloads/images/audio.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_2.addTab(self.tab_7, icon4, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_8)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.listWidget_3 = QtGui.QListWidget(self.tab_8)
        self.listWidget_3.setObjectName(_fromUtf8("listWidget_3"))
        self.gridLayout_7.addWidget(self.listWidget_3, 0, 0, 1, 1)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("../Downloads/images/video.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_2.addTab(self.tab_8, icon5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tab_6)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.listWidget_4 = QtGui.QListWidget(self.tab_6)
        self.listWidget_4.setObjectName(_fromUtf8("listWidget_4"))
        self.gridLayout_8.addWidget(self.listWidget_4, 0, 0, 1, 1)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("../Downloads/images/zip.jpeg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_2.addTab(self.tab_6, icon6, _fromUtf8(""))
        self.gridLayout_4.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("../Downloads/images/finisheddownload.jpeg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_2, icon7, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.listWidget_5 = QtGui.QListWidget(self.tab_4)
        self.listWidget_5.setObjectName(_fromUtf8("listWidget_5"))
        self.gridLayout_9.addWidget(self.listWidget_5, 0, 0, 1, 1)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("../Downloads/images/queue.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_4, icon8, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 728, 25))
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menu_View = QtGui.QMenu(self.menubar)
        self.menu_View.setObjectName(_fromUtf8("menu_View"))
        self.menuTool_Bar = QtGui.QMenu(self.menu_View)
        self.menuTool_Bar.setObjectName(_fromUtf8("menuTool_Bar"))
        self.menu_Downloads = QtGui.QMenu(self.menubar)
        self.menu_Downloads.setObjectName(_fromUtf8("menu_Downloads"))
        self.menu_Help = QtGui.QMenu(self.menubar)
        self.menu_Help.setObjectName(_fromUtf8("menu_Help"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.statusbar.setAutoFillBackground(False)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setAutoFillBackground(False)
        self.toolBar.setIconSize(QtCore.QSize(60, 30))
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_Add_URL = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("../Downloads/images/addurl.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Add_URL.setIcon(icon9)
        self.action_Add_URL.setIconVisibleInMenu(True)
        self.action_Add_URL.setObjectName(_fromUtf8("action_Add_URL"))
        self.action_Resume = QtGui.QAction(MainWindow)
        self.action_Resume.setCheckable(True)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8("../Downloads/images/stopall.jpeg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Resume.setIcon(icon10)
        self.action_Resume.setIconVisibleInMenu(True)
        self.action_Resume.setObjectName(_fromUtf8("action_Resume"))
        self.action_Delete_All = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8("../Downloads/images/deleteall.jpeg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Delete_All.setIcon(icon11)
        self.action_Delete_All.setIconVisibleInMenu(True)
        self.action_Delete_All.setObjectName(_fromUtf8("action_Delete_All"))
        self.action_Schedule = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8("../Downloads/images/schedule.jpeg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Schedule.setIcon(icon12)
        self.action_Schedule.setIconVisibleInMenu(True)
        self.action_Schedule.setObjectName(_fromUtf8("action_Schedule"))
        self.action_Exit = QtGui.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8("../Downloads/images/exit.jpeg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Exit.setIcon(icon13)
        self.action_Exit.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.action_Exit.setIconVisibleInMenu(True)
        self.action_Exit.setObjectName(_fromUtf8("action_Exit"))
        self.actionArrange_Files = QtGui.QAction(MainWindow)
        self.actionArrange_Files.setObjectName(_fromUtf8("actionArrange_Files"))
        self.actionTab = QtGui.QAction(MainWindow)
        self.actionTab.setObjectName(_fromUtf8("actionTab"))
        self.actionHide = QtGui.QAction(MainWindow)
        self.actionHide.setObjectName(_fromUtf8("actionHide"))
        self.actionVisible = QtGui.QAction(MainWindow)
        self.actionVisible.setObjectName(_fromUtf8("actionVisible"))
        self.actionRecent_Downloads = QtGui.QAction(MainWindow)
        self.actionRecent_Downloads.setObjectName(_fromUtf8("actionRecent_Downloads"))
        self.actionAll_Downloads = QtGui.QAction(MainWindow)
        self.actionAll_Downloads.setObjectName(_fromUtf8("actionAll_Downloads"))
        self.actionDelete_History = QtGui.QAction(MainWindow)
        self.actionDelete_History.setObjectName(_fromUtf8("actionDelete_History"))
        self.actionCancelled_Downloads = QtGui.QAction(MainWindow)
        self.actionCancelled_Downloads.setObjectName(_fromUtf8("actionCancelled_Downloads"))
        self.actionAbout_IDM = QtGui.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8("../Downloads/images/help.jpeg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout_IDM.setIcon(icon14)
        self.actionAbout_IDM.setIconVisibleInMenu(True)
        self.actionAbout_IDM.setObjectName(_fromUtf8("actionAbout_IDM"))
        self.actionAbout_Site_Grabber = QtGui.QAction(MainWindow)
        self.actionAbout_Site_Grabber.setIcon(icon14)
        self.actionAbout_Site_Grabber.setIconVisibleInMenu(True)
        self.actionAbout_Site_Grabber.setObjectName(_fromUtf8("actionAbout_Site_Grabber"))
        self.actionAbout_Speed_Limiter = QtGui.QAction(MainWindow)
        self.actionAbout_Speed_Limiter.setIcon(icon14)
        self.actionAbout_Speed_Limiter.setIconVisibleInMenu(True)
        self.actionAbout_Speed_Limiter.setObjectName(_fromUtf8("actionAbout_Speed_Limiter"))
        self.actionSped_Limiter = QtGui.QAction(MainWindow)
        self.actionSped_Limiter.setCheckable(True)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8("../Downloads/images/speedlimiter.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSped_Limiter.setIcon(icon15)
        self.actionSped_Limiter.setIconVisibleInMenu(True)
        self.actionSped_Limiter.setObjectName(_fromUtf8("actionSped_Limiter"))
        self.actionSite_Grabber = QtGui.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8("../Downloads/images/sitegrabber.jpeg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSite_Grabber.setIcon(icon16)
        self.actionSite_Grabber.setIconVisibleInMenu(False)
        self.actionSite_Grabber.setObjectName(_fromUtf8("actionSite_Grabber"))
        self.actionPause_All = QtGui.QAction(MainWindow)
        self.actionPause_All.setIcon(icon2)
        self.actionPause_All.setIconVisibleInMenu(True)
        self.actionPause_All.setObjectName(_fromUtf8("actionPause_All"))
        self.actionReume_All = QtGui.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8("../Downloads/images/resume download.jpeg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReume_All.setIcon(icon17)
        self.actionReume_All.setIconVisibleInMenu(True)
        self.actionReume_All.setObjectName(_fromUtf8("actionReume_All"))
        self.actionStop = QtGui.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8("../Downloads/images/stop.jpeg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop.setIcon(icon18)
        self.actionStop.setObjectName(_fromUtf8("actionStop"))
        self.actionPause = QtGui.QAction(MainWindow)
        self.actionPause.setIcon(icon2)
        self.actionPause.setObjectName(_fromUtf8("actionPause"))
        self.actionResume = QtGui.QAction(MainWindow)
        self.actionResume.setIcon(icon17)
        self.actionResume.setObjectName(_fromUtf8("actionResume"))
        self.menuFile.addAction(self.action_Add_URL)
        self.menuFile.addAction(self.actionPause_All)
        self.menuFile.addAction(self.actionReume_All)
        self.menuFile.addAction(self.action_Resume)
        self.menuFile.addAction(self.action_Schedule)
        self.menuFile.addAction(self.action_Delete_All)
        self.menuFile.addAction(self.actionSped_Limiter)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_Exit)
        self.menuTool_Bar.addAction(self.actionHide)
        self.menuTool_Bar.addAction(self.actionVisible)
        self.menu_View.addAction(self.actionArrange_Files)
        self.menu_View.addAction(self.menuTool_Bar.menuAction())
        self.menu_View.addAction(self.actionTab)
        self.menu_Downloads.addAction(self.actionRecent_Downloads)
        self.menu_Downloads.addAction(self.actionAll_Downloads)
        self.menu_Downloads.addAction(self.actionCancelled_Downloads)
        self.menu_Downloads.addAction(self.actionDelete_History)
        self.menu_Help.addAction(self.actionAbout_IDM)
        self.menu_Help.addAction(self.actionAbout_Site_Grabber)
        self.menu_Help.addAction(self.actionAbout_Speed_Limiter)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu_View.menuAction())
        self.menubar.addAction(self.menu_Downloads.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())
        self.toolBar.addAction(self.action_Add_URL)
        self.toolBar.addAction(self.actionPause_All)
        self.toolBar.addAction(self.actionReume_All)
        self.toolBar.addAction(self.action_Resume)
        self.toolBar.addAction(self.action_Delete_All)
        self.toolBar.addAction(self.actionSite_Grabber)
        self.toolBar.addAction(self.action_Schedule)
        self.toolBar.addAction(self.actionSped_Limiter)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QObject.connect(self.action_Exit, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Internet Download Manager", None))
        MainWindow.setWhatsThis(_translate("MainWindow", "This is a download manager", None))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "New Row", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Speed", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Time Left", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Progress", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Size", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Category", None))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "File  Name", None))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Options", None))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Ongoing Downloads", None))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "This shows the ongoing downloads", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Paused Downloads", None))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "This shows all paused downloads", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Documents", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("MainWindow", "Audio", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("MainWindow", "Video", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "Zipped Files", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Finished downloads", None))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "This shows all finished downloads", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", " Queued Downloads", None))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "This shows all queued downloads", None))
        self.menuFile.setTitle(_translate("MainWindow", "&File", None))
        self.menu_View.setTitle(_translate("MainWindow", "&View", None))
        self.menuTool_Bar.setTitle(_translate("MainWindow", "Tool Bar", None))
        self.menu_Downloads.setTitle(_translate("MainWindow", "&Downloads", None))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.action_Add_URL.setText(_translate("MainWindow", "&Add URL", None))
        self.action_Resume.setText(_translate("MainWindow", "&Stop ALl", None))
        self.action_Delete_All.setText(_translate("MainWindow", "&Delete All", None))
        self.action_Schedule.setText(_translate("MainWindow", "&Schedule", None))
        self.action_Exit.setText(_translate("MainWindow", "Exit", None))
        self.action_Exit.setShortcut(_translate("MainWindow", "Ctrl+Z", None))
        self.actionArrange_Files.setText(_translate("MainWindow", "Arrange Files", None))
        self.actionTab.setText(_translate("MainWindow", "Tab", None))
        self.actionHide.setText(_translate("MainWindow", "Hide ", None))
        self.actionVisible.setText(_translate("MainWindow", "Visible", None))
        self.actionRecent_Downloads.setText(_translate("MainWindow", "Recent Downloads", None))
        self.actionAll_Downloads.setText(_translate("MainWindow", "All Downloads", None))
        self.actionDelete_History.setText(_translate("MainWindow", "Delete History", None))
        self.actionCancelled_Downloads.setText(_translate("MainWindow", "Cancelled Downloads", None))
        self.actionAbout_IDM.setText(_translate("MainWindow", "About IDM", None))
        self.actionAbout_Site_Grabber.setText(_translate("MainWindow", "About Site Grabber", None))
        self.actionAbout_Speed_Limiter.setText(_translate("MainWindow", "About Speed Limiter", None))
        self.actionSped_Limiter.setText(_translate("MainWindow", "Sped Limiter", None))
        self.actionSite_Grabber.setText(_translate("MainWindow", "Site Grabber", None))
        self.actionSite_Grabber.setToolTip(_translate("MainWindow", "Grab a site", None))
        self.actionPause_All.setText(_translate("MainWindow", "Pause All", None))
        self.actionReume_All.setText(_translate("MainWindow", "Reume All", None))
        self.actionStop.setText(_translate("MainWindow", "Stop", None))
        self.actionPause.setText(_translate("MainWindow", "Pause", None))
        self.actionResume.setText(_translate("MainWindow", "Resume", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

